### ISSUE TITLE
User management / Profil - Saját profil megtekintése

### ISSUE THREAD

**Issue by feco-csiha** [flowacademyhu/eta-company-calendar#14]
#2 
- Saját profil oldal megvalósítása, adatok kiírása.,
- Profil menüpont létrehozása. Itt találhatóak meg az adatok
- Módosítás gomb megjelenítése.

Megjelenítendő adatok:
-A dolgozó neve
-Munkakör, osztály, csoport
-Közvetlen felettes

**Comment by muller93** [comment]
További issuekra bontom
