### ISSUE TITLE
Új User(dolgozó) felvétele

### ISSUE THREAD

**Issue by muller93** [flowacademyhu/eta-company-calendar#22]
#2 
A Profilom menüpontba szükség van egy gombra, amivel új Usert tudunk felvenni.
Az új dolgozó felvételéhez szükséges adatok:
-	a dolgozó neve
-	munkakör, osztály, csoport
-	közvetlen felettes
Informatív hibakezelés szükséges

**Comment by urbanjozsef88** [comment]
Ez az issue a #56-ban lett megoldva
