### ISSUE TITLE
Service rétegbeli exception dobás átírása exception handlerekkel

### ISSUE THREAD

**Issue by karolyp** [flowacademyhu/eta-company-calendar#93]
Pl.: amikor egy Usert nem találunk, ne dobjunk HTTP kóddal exceptiont, vagy RuntimeExceptiont, hanem vezessünk be egy új RuntimeException osztályból származó osztályt (UserNotFoundException), amit egy ControllerAdvice exception handler osztály lekezel, és visszatér a megfelelő HTTP státusszal.

**Comment by noriszucs** [comment]
@borosr

**Comment by noriszucs** [comment]
Mit szólnál Karesz ha a ResponseStatusException-ból öröklődnénk? És akkor nem kell ControllerAdvice. Így mindent le tudnánk kezelni.

**Comment by karolyp** [comment]
Nem szeretném, ha a controller réteghez kapcsolódó osztályok (úgy, mint a ResponseStatusException) még akár egy abból származó exceptionként bekerüljön a service rétegbe. Ez azért lenne fontos, hogy elválasszuk a két réteget egymástól.

**Comment by karolyp** [comment]
@borosr Te mit gondolsz erről, ez valid feladat lehet?

**Comment by borosr** [comment]
Hopsz, bocsi like-olni akartam amit írtál. Alapból tőlem származott a származtatásos ötlet, hogy kevesebb kód legyen. Viszont értem és egyezem az indokoddal, szóval mehet a `@ControllerAdvice` és a RuntimeException-ök.

**Comment by noriszucs** [comment]
okés, folyamatban
